SimpleProduct/Controllers/SProductDBsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SimpleProduct.Models;

namespace SimpleProduct.Controllers
{
    public class SProductDBsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: SProductDBs
        public ActionResult Index()
        {
            return View(db.SProductDBs.ToList());
        }

        // GET: SProductDBs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SProductDB sProductDB = db.SProductDBs.Find(id);
            if (sProductDB == null)
            {
                return HttpNotFound();
            }
            return View(sProductDB);
        }

        // GET: SProductDBs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SProductDBs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,make,model,year,unitPrice,NumberInStock")] SProductDB sProductDB)
        {
            if (ModelState.IsValid)
            {
                db.SProductDBs.Add(sProductDB);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sProductDB);
        }

        // GET: SProductDBs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SProductDB sProductDB = db.SProductDBs.Find(id);
            if (sProductDB == null)
            {
                return HttpNotFound();
            }
            return View(sProductDB);
        }

        // POST: SProductDBs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,make,model,year,unitPrice,NumberInStock")] SProductDB sProductDB)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sProductDB).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sProductDB);
        }

        // GET: SProductDBs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SProductDB sProductDB = db.SProductDBs.Find(id);
            if (sProductDB == null)
            {
                return HttpNotFound();
            }
            return View(sProductDB);
        }

        // POST: SProductDBs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SProductDB sProductDB = db.SProductDBs.Find(id);
            db.SProductDBs.Remove(sProductDB);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SimpleProduct/Views/Shared/FooterPartial.cshtml
    <footer>
        <p>&copy; @DateTime.Now.Year - Simply Products </p>
    </footer>

SimpleProduct/Views/Shared/NavPartial.cshtml
<ul class="nav navbar-nav">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
    <li>@Html.ActionLink("About", "About", "Home")</li>
    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    <li>@Html.ActionLink("Products", "Index", "SProductDBs")</li>
</ul>

SimpleProduct/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @Html.Partial("NavPartial")
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>


    <div class="container body-content">
        @RenderBody()
        <hr />
        @Html.Partial("FooterPartial")
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SimpleProduct/Views/Shared/_LayoutCustomized.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        body {
            background-color: lightblue;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @Html.Partial("NavPartial")
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>


    <div class="container body-content">
        @RenderBody()
        <hr />
        @Html.Partial("FooterPartial")
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>